export const ConstData = [
    {"product":"Milk Bars","category":"Bars"	,"cost_per_box":5.26 },
    {"product":"50% Dark Bites","category":"Bites","cost_per_box":7.48 },
    {"product":"Almond Choco","category":"Bars","cost_per_box":5.15 },
    {"product":"Raspberry Choco","category":"Bars","cost_per_box":3.85 },
    {"product":"Mint Chip Choco","category":"Bars"	,"cost_per_box":5.72 },
    {"product":"Eclairs"	,"category":"Bites","cost_per_box":6.31 },
    {"product":"Drinking Coco","category":	"Other"	,"cost_per_box":9.94 },
    {"product":"99% Dark & Pure"	,"category":"Bars"	,"cost_per_box":7.73 },
    {"product":"Orange Choco"	,"category":"Bars"	,"cost_per_box":3.68 },
    {"product":"Spicy Special Slims"	,"category":"Bites",	"cost_per_box":8.22 },
    {"product":"After Nines"	,"category":"Bites"	,"cost_per_box":10.23 },
    {"product":"Fruit & Nut Bars"	,"category":"Bars",	"cost_per_box":4.74 },
    {"product":"85% Dark Bars",	"category":"Bars",	"cost_per_box":10.51 },
    {"product":"White Choc"	,"category":"Other"	,"cost_per_box":6.43 },
    {"product":"Baker's Choco Chips"	,"category":"Bars"	,"cost_per_box":12.41 },
    {"product":"Organic Choco Syrup"	,"category":"Other",	"cost_per_box":9.57}, 
    {"product":"Caramel Stuffed Bars"	,"category":"Bars"	,"cost_per_box":8.43 },
    {"product":"Manuka Honey Choco"	,"category":"Other"	,"cost_per_box":6.80 },
    {"product":"70% Dark Bites"	,"category":"Bites"	,"cost_per_box":5.04 },
    {"product":"Smooth Silky Salty"	,"category":"Bars"	,"cost_per_box":2.76 },
    {"product":"Choco Coated Almonds",	"category":"Bites",	"cost_per_box":3.32 },
    {"product":"Peanut Butter Cubes",	"category":"Bites"	,"cost_per_box":2.65}
]